### ISSUE TITLE
Importing resources causes the provider plugin to crash

### ISSUE THREAD

**Issue by thmzlt** [latitudesh/terraform-provider-latitudesh#41]
## Describe the bug
I want to import a `latitudesh_project` that was created using the web interface, but when I run `terraform import latitudesh_project.main XXX`, I get an error.

### Affected Resource(s)

- latitudesh_project (other resources are also affected)

### Expected Behavior

I expected the project to be imported into my Terraform state.

### Actual Behavior

I see the following error message on stdout:

```
latitudesh_project.main: Importing from ID "MY_PROJECT_ID"...
latitudesh_project.main: Import prepared!
  Prepared latitudesh_project for import
latitudesh_project.main: Refreshing state... [id=MY_PROJECT_ID]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-latitudesh_v0.2.7 plugin:

panic: interface conversion: interface {} is nil, not *latitude.Client

goroutine 13 [running]:
github.com/latitudesh/terraform-provider-latitudesh/latitudesh.resourceProjectRead({0x100c77ae0?, 0x140003ce630?}, 0x0?, {0x0?, 0x0?})
	github.com/latitudesh/terraform-provider-latitudesh/latitudesh/resource_project.go:81 +0x438
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x140002c08c0, {0x100c77ae0, 0x140003ce630}, 0xd?, {0x0, 0x0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:724 +0xec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140002c08c0, {0x100c77ae0, 0x140003ce630}, 0x14000189040, {0x0, 0x0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400039a450, {0x100c77ae0?, 0x140003ce510?}, 0x1400019c940)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:613 +0x40c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140002ea8c0, {0x100c77ae0?, 0x14000187c50?}, 0x1400010ed80)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x3ec
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x100c42ea0?, 0x140002ea8c0}, {0x100c77ae0, 0x14000187c50}, 0x140001cc310, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400025c1e0, {0x100c7a800, 0x1400018a9c0}, 0x140001458c0, 0x14000393ef0, 0x1010da870, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0x9d8
google.golang.org/grpc.(*Server).handleStream(0x1400025c1e0, {0x100c7a800, 0x1400018a9c0}, 0x140001458c0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x298

Error: The terraform-provider-latitudesh_v0.2.7 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

Import `latitudesh_project.main` with the following Terraform module:

```tf
terraform {
  required_providers {
    latitudesh = {
      source  = "latitudesh/latitudesh"
      version = "0.2.7"
    }
  }
}

resource "latitudesh_project" "main" {
  name        = "MY_PROJECT_NAME"
  description = ""
  environment = "Production"
}
```

**Comment by ynhummel** [comment]
@thmzlt Thanks for reaching out!
The problem might be that you haven't defined your auth_token for connecting to our servers; you can add it right beside the `terraform` block.
```
terraform {
  required_providers {
    latitudesh = {
      source  = "latitudesh/latitudesh"
      version = "0.2.7"
    }
  }
}

# Define the authentication token for using our services
provider "latitudesh" {
  auth_token = "<YOUR-API-TOKEN>"
}
```
You can generate the API token at our [dashboard](https://www.latitude.sh/dashboard) by acessing the `API Keys` menu under `Settings & Billing`.
I will work to improve this error message.

Now, if that's not the cause of your error, please follow up on this issue so we can continue to investigate.

**Comment by esoubihe** [comment]
Alternatively, when running tf locally you can export the token

`export LATITUDESH_AUTH_TOKEN=<API_TOKEN>`

**Comment by thmzlt** [comment]
Thanks. I thought I had `LATITUDESH_AUTH_TOKEN` exported but didn't. Re-exporting the token fixed it.

**Comment by esoubihe** [comment]
Lovely! Don't hesitate to open a new issue if you need anything else.
